name: event_tracker
description: A simple Flutter app for tracking events
version: 2.0.0+3

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^1.0.0
  dropdown_search: 5.0.6
  url_launcher: ^6.2.5
  file_picker: ^10.2.0
  path_provider: ^2.1.2
  share_plus: ^7.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/HCIcon512PNG.png

flutter_icons:
  android: true
  ios: true
  image_path_android: "assets/icon/HCIcon512PNG.png"
  image_path_ios: "assets/icon/HCIcon512PNG.png"
  adaptive_icon_background: "#FFFFFF"

dependency_overrides:
  share_plus: 7.2.2
  dropdown_search: 5.0.6