name: event_tracker
description: A simple Flutter app for tracking events
version: 2.0.0+2

environment:
  sdk: '^3.8.0'

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  fl_chart: ^0.63.0
  dropdown_search: ^5.0.6
  url_launcher: ^6.2.5
  file_selector: ^1.0.3
  file_selector_windows: ^0.9.3+4
  file_selector_macos: ^0.9.4+3
  file_selector_linux: ^0.9.3+2
  path_provider: ^2.1.2
  share_plus: ^7.2.1
  flutter_launcher_icons: ^0.13.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/icon/HCIcon512PNG.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon/HCIcon512PNG.png"  # Replace with your actual icon path
